### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.sourceforge.xournal#1]
<div align=center>

![captura de tela de 2018-05-16 09-18-06](https://user-images.githubusercontent.com/26097419/40116467-22523704-58ea-11e8-9a6c-3cf63c80fedf.png)

**Comment by jlelse** [comment]
I think the latest commit fixed that. Could you try updating and check if it's still a problem?

**Comment by LeandroStanger** [comment]
<div align=center>

![captura de tela de 2018-05-16 10-29-21](https://user-images.githubusercontent.com/26097419/40119834-16889d1e-58f4-11e8-98f3-8bff985ea0fc.png)
